/*
 * This source file was generated by the Gradle 'init' task
 */
package sti.oop;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
        // JFrame window = new JFrame();
        // window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // window.setResizable(false);
        // window.setTitle("That TIme I Became a Farming Game Dev To Save The World");
        
        // GamePanel gamePanel = new GamePanel();
        // window.add(gamePanel);
        // window.pack();
        
        // window.setLocationRelativeTo(null);
        // window.setVisible(true);
        // gamePanel.startGameThread();
        // System.out.println(new App().getGreeting());
    }

    @Override
    public void start(Stage stage) throws Exception {
        // HBox root = new HBox();
        // Button b1 = new Button("tolol");
        // root.getChildren().add(b1);
        // Scene sc = new Scene(root);
        // stage.setScene(sc);
        // stage.show();
    }
}
