/*
 * This source file was generated by the Gradle 'init' task
 */
package sti.oop;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
// import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class App extends Application {
    final public static int originalTileSize = 16;
    final public static int scale = 2;
    final public static int tileSize = originalTileSize * scale;
    final public static int maxScreenCol = 32;
    final public static int maxScreenRow = 32;
    final public static int screenWidth = tileSize * maxScreenCol;
    final public static int screenHeight = tileSize * maxScreenRow;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        System.out.println("Prism MaxVRAM set to: " + System.getProperty("prism.maxvram"));
        System.out.println("Prism MinVRAM set to: " + System.getProperty("prism.minvram"));
        Parent root = FXMLLoader.load(getClass().getResource("/views/MainMenu.fxml"));
        stage.setScene(new Scene(root));
        stage.setTitle("Spakbor Hills");
        stage.show();

        // Player player = new Player("Aris", Gender.MALE, "Bebek Om Aris");
        // Farm farm = new Farm("Bebek Om Aris", player);
        // farm.run(stage); 
    }
}